### ISSUE TITLE
(NameError) undefined local variable or method `__dir__' 

### ISSUE THREAD

**Issue by qoyyim** [vaihtovirta/botup#4]
```
~/.rvm/gems/ruby-1.9.3-p327/gems/botup-0.3.1/lib/botup/file_processor.rb:57:in `config_folder': undefined local variable or method `__dir__' for #<Botup::FileProcessor:0x007fc86b9745d8> (NameError)
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/botup-0.3.1/lib/botup/file_processor.rb:27:in `prepare_files'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/botup-0.3.1/lib/botup/file_processor.rb:14:in `call'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/botup-0.3.1/lib/botup.rb:7:in `generate'
    from ~/.rvm/gems/ruby-1.9.3-p327/gems/botup-0.3.1/bin/botup:5:in `<top (required)>'
    from ~/.rvm/gems/ruby-1.9.3-p327/bin/botup:19:in `load'
    from ~/.rvm/gems/ruby-1.9.3-p327/bin/botup:19:in `<main>'
    from ~/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
```

**Comment by qoyyim** [comment]
fixed by updating ruby version
